### ISSUE TITLE
Incompileable on Arch Linux x86_64

### ISSUE THREAD

**Issue by voxelias** [MFrcoin/MFCoin#1]
build log attached

[mfcoin_buildlog.txt](https://github.com/MFrcoin/MFCoin/files/1292479/mfcoin_buildlog.txt)

**Comment by MFrcoin** [comment]
soon

**Comment by eventengine** [comment]
how soon, dude??? almost 5 month! its ridiculous! >.<

**Comment by alex-mamchenkov** [comment]
@Lowentwickler What is the exact problem? buildlog only shows warnings, no errors. Can you please share an error?
