### ISSUE TITLE
Does not compile with OpenSSL 1.0.1

### ISSUE THREAD

**Issue by evgeny-gist** [MFrcoin/MFCoin#12]
Ubuntu 16.04
`OpenSSL 1.0.1 14 Mar 2012 (Library: OpenSSL 1.0.2g  1 Mar 2016)`
make log in .txt file

[log.txt](https://github.com/MFrcoin/MFCoin/files/3145905/log.txt)

**Comment by Sagleft** [comment]
1. попробуй версию 1.0.1l:
https://www.openssl.org/source/openssl-1.0.1l.tar.gz

2. попробуй не собирать из исходников, а поставить по обычному.
Нашел вариант по другой монете.
если openssl установлен, удалить:
```
sudo apt-get remove libssl-dev
```
затем поменять stretch на jessie
```
sudo nano /etc/apt/sources.list
```
затем
```
sudo apt-get update
sudo apt-get install libssl-dev
```
если захочешь сохранить версию openssl, чтобы не обновлялась:
```
sudo apt-mark hold libssl-dev
```
