### ISSUE TITLE
Crash on linux

### ISSUE THREAD

**Issue by kr1z1s** [MFrcoin/MFCoin#14]
mfcoind: chainparams.cpp:399: CTestNetParams::CTestNetParams(): Assertion `consensus.hashGenesisBlock == uint256S("0xb98c3956a2fc4ad9027cd8858dc32fba36f5bfdb01e64856879d393f34297013")' failed.
Аварийный останов (сделан дамп памяти)

Using you precompiled binary files for linux

**Comment by himikk** [comment]
Hey developers,
Is there any solution?

**Comment by pinpins** [comment]
is there any solution to above?
