### ISSUE TITLE
Build error on Ubuntu 16.04 (libleveldb.a, libmemenv.a files not found)

### ISSUE THREAD

**Issue by akazakou** [MFrcoin/MFCoin#2]
`akazakou@zx386:/tmp/MFCoin$ uname -a
Linux zx386 4.10.0-35-generic #39~16.04.1-Ubuntu SMP Wed Sep 13 09:02:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

`g++ -m64 -fstack-protector-all -Wl,-O1 -o MFCoin-qt build/bitcoin.o build/bitcoingui.o build/transactiontablemodel.o build/addresstablemodel.o build/optionsdialog.o build/sendcoinsdialog.o build/coincontroldialog.o build/coincontroltreewidget.o build/addressbookpage.o build/signverifymessagedialog.o build/aboutdialog.o build/editaddressdialog.o build/bitcoinaddressvalidator.o build/alert.o build/version.o build/sync.o build/util.o build/hash.o build/netbase.o build/key.o build/script.o build/main.o build/init.o build/irc.o build/net.o build/bloom.o build/checkpoints.o build/addrman.o build/db.o build/walletdb.o build/clientmodel.o build/guiutil.o build/transactionrecord.o build/optionsmodel.o build/monitoreddatamapper.o build/transactiondesc.o build/transactiondescdialog.o build/bitcoinstrings.o build/bitcoinamountfield.o build/wallet.o build/keystore.o build/transactionfilterproxy.o build/transactionview.o build/walletmodel.o build/walletview.o build/walletstack.o build/walletframe.o build/bitcoinrpc.o build/rpcdump.o build/rpcnet.o build/rpcmining.o build/rpcwallet.o build/rpcblockchain.o build/rpcrawtransaction.o build/overviewpage.o build/csvmodelwriter.o build/crypter.o build/sendcoinsentry.o build/qvalidatedlineedit.o build/bitcoinunits.o build/qvaluecombobox.o build/askpassphrasedialog.o build/protocol.o build/notificator.o build/paymentserver.o build/rpcconsole.o build/scrypt.o build/noui.o build/leveldb.o build/txdb.o build/splashscreen.o build/moc_bitcoingui.o build/moc_transactiontablemodel.o build/moc_addresstablemodel.o build/moc_optionsdialog.o build/moc_sendcoinsdialog.o build/moc_coincontroldialog.o build/moc_coincontroltreewidget.o build/moc_addressbookpage.o build/moc_signverifymessagedialog.o build/moc_aboutdialog.o build/moc_editaddressdialog.o build/moc_bitcoinaddressvalidator.o build/moc_clientmodel.o build/moc_guiutil.o build/moc_optionsmodel.o build/moc_monitoreddatamapper.o build/moc_transactiondesc.o build/moc_transactiondescdialog.o build/moc_bitcoinamountfield.o build/moc_transactionfilterproxy.o build/moc_transactionview.o build/moc_walletmodel.o build/moc_walletview.o build/moc_walletstack.o build/moc_walletframe.o build/moc_overviewpage.o build/moc_csvmodelwriter.o build/moc_sendcoinsentry.o build/moc_qvalidatedlineedit.o build/moc_bitcoinunits.o build/moc_qvaluecombobox.o build/moc_askpassphrasedialog.o build/moc_notificator.o build/moc_paymentserver.o build/moc_rpcconsole.o build/moc_macnotificationhandler.o build/moc_splashscreen.o build/qrc_bitcoin.o    -L/usr/lib/x86_64-linux-gnu -lminiupnpc /tmp/MFCoin/src/leveldb/libleveldb.a /tmp/MFCoin/src/leveldb/libmemenv.a -lrt -lssl -lcrypto -ldb_cxx -lboost_system -lboost_filesystem -lboost_program_options -lboost_thread -lpthread -lQtGui -lQtNetwork -lQtCore 
g++: error: /tmp/MFCoin/src/leveldb/libleveldb.a: Нет такого файла или каталога
g++: error: /tmp/MFCoin/src/leveldb/libmemenv.a: Нет такого файла или каталога
Makefile:316: ошибка выполнения рецепта для цели «MFCoin-qt»
make: *** [MFCoin-qt] Ошибка 1
`

**Comment by UserS-56** [comment]
либо:
cd ~/MFCoin/src/
rm -rf leveldb
mv leveldb-lin/ leveldb
далее пробуете снова собрать.

либо: воспользоваться этим https://github.com/voidale/MFCoinLinux

**Comment by akazakou** [comment]
@UserS-56 спасибо за попытку, но результат тот же:

```
g++: error: /tmp/MFCoin/src/leveldb/libleveldb.a: Нет такого файла или каталога
g++: error: /tmp/MFCoin/src/leveldb/libmemenv.a: Нет такого файла или каталога
Makefile:316: ошибка выполнения рецепта для цели «MFCoin-qt»
```

**Comment by UserS-56** [comment]
понял. простите, моя ошибка.
вот:
cd /tmp/MFCoin/src/
rm -rf leveldb
mv leveldb-lin/ leveldb
далее 
cd /tmp/MFCoin/
./qmake

**Comment by UserS-56** [comment]
все дело в том, что папка  leveldb изначально под win ос.
поэтому требуется удалить её, а вот папку  leveldb-lin переименовать в  leveldb
после этого кошелек нормально собирается, если хватит остальных библиотек. ну там выложите ошибки, подскажу что еще требуется доставить.

**Comment by MFrcoin** [comment]
Installing MFCoind from source :: Ubuntu 16
This Howto demonstrates how to compile MFCoind from source under Ubuntu 16 including
all dependencies, configure and run the node.

Assumption: all commands are executed under root

Edit this section
Swap memory
In order for MFCoind to compile successfully, you need to make sure you have enough RAM and/or
sufficient swap space. If is recommended to have at least 1GB swap in any case, so to get it, run the
following commands on a fresh system once and it will make and configure swap and make sure it is
enabled during boot:

dd if=/dev/zero of=/swapfile bs=1024 count=1048576
chmod 0600 /swapfile
mkswap /swapfile
echo "/swapfile swap swap defaults 0 0" >> /etc/fstab
swapon /swapfile
The above will create 1GB swap space in /swapfile

Edit this section
Dependancies
MFCoind requires few packages to compile and run. The below will setup custom repo with those (old) deps 
and will install them in the system:

add-apt-repository ppa:bitcoin/bitcoin
apt-get update
apt-get install build-essential libssl-dev libdb4.8-dev libdb4.8++-dev libboost1.58-dev libboost1.58-all-dev libminiupnpc-dev
NOTE on boost: Only the following are required from boost: boost_system, boost_filesystem, boost_program_options, boost_thread and their deps,
so later on need to replace libboost1.58-all-dev with corresponding separate packages to bring less to the system

Edit this section
Prepare and build
Now as we are ready, let's fetch the MFCoin repo, do couple of tricks around to prepare and then build the MFCoind

git clone https://github.com/MFrcoin/MFCoin.git
cd MFCoin/src
make USE_UPNP=0 USE_IPV6=0 -f makefile.unix
Edit this section
Installation and Cleanup
As we don't really want to keep all those sources and have in order, lets make MFCoind discover-able in our PATH and clean the rest

mv MFCoind /usr/local/bin/
cd ../../
rm -rm MFCoin
Edit this section
First Run
For MFCoind to run, we need to specify couple of config options, and those can be generated
automatically on first run:

MFCoind
The part of the out put will be:

rpcuser=MFCoinrpc
rpcpassword=4N3PdB1Day4W1rb59USU48LwfMX99XajiKwnbu1s7qBK
with prcpassword being some random string. Put both lines in ~/.MFCoind/MFCoin.conf

Edit this section
Daemon run
Now as we have all in order, each time you boot up, run the following command:

MFCoind -daemon
