### ISSUE TITLE
MFCoin-qt.exe Ошибка: Обнаружен вирус.

### ISSUE THREAD

**Issue by sunra** [MFrcoin/MFCoin#3]
При скачивании в Crome. Windows 10

**Comment by RusDarkStar** [comment]
Привет , а по сувенирке что-то известно ???

2017-12-22 21:10 GMT+03:00 sunra <notifications@github.com>:

**Comment by MFrcoin** [comment]
It's normal for cryptocurrency soft. Litecoin client throws similar flags as well: https://www.virustotal.com/#/file/d3b1628f12050582480f13d232ffe5b62caae9d4d7ac42c1559b706a50884818/detection
